services:
  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATA: 
  
  pgadmin:
    image: dpage/pgadmin4:8.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_ENABLE_TLS: true
    depends_on:
      - postgres
  
  lowpressurezone.api:
    container_name: lpz-api
    image: ${DOCKER_REGISTRY-}lowpressurezoneapi
    build:
      context: ../..
      dockerfile: src/server/LowPressureZone.Api/Dockerfile
  
  lowpressurezone.client:
    container_name: lpz-client

volumes:
  lpz-data:
  lpz-pgadmin-data:
  node-modules:
