// <auto-generated />
using System;
using System.Collections.Generic;
using LowPressureZone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LowPressureZone.Data.Migrations;

[DbContext(typeof(DataContext))]
[Migration("20260829190621_AddNewScheduleAndCommunity")]
partial class _20260829190621_AddNewScheduleAndCommunity
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-preview.6.26359.118")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("LowPressureZone.Domain.CommunityAggregate.Community", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<string>("SocialUrl")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.HasKey("Id");

                b.ToTable("NewCommunities");
            });

        modelBuilder.Entity("LowPressureZone.Domain.CommunityAggregate.RelationshipEntity.Relationship", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CommunityId")
                    .HasColumnType("uuid");

                b.Property<bool>("IsOrganizer")
                    .HasColumnType("boolean");

                b.Property<bool>("IsPerformer")
                    .HasColumnType("boolean");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CommunityId");

                b.ToTable("Relationship");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Broadcast", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("AzuraCastBroadcastId")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsArchived")
                    .HasColumnType("boolean");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("Broadcasts");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Community", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Url")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.ToTable("Communities");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.CommunityRelationship", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CommunityId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsOrganizer")
                    .HasColumnType("boolean");

                b.Property<bool>("IsPerformer")
                    .HasColumnType("boolean");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("CommunityId");

                b.ToTable("CommunityRelationships");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.HourlySlot", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int?>("AzuraCastMediaId")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("PerformerId")
                    .HasColumnType("uuid");

                b.Property<Guid>("ScheduleId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Subtitle")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("UploadedFileName")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");

                b.HasKey("Id");

                b.HasIndex("PerformerId");

                b.HasIndex("ScheduleId");

                b.ToTable("Timeslots");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Schedule", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid?>("CommunityId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<bool>("IsOrganizersOnly")
                    .HasColumnType("boolean");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("CommunityId");

                b.ToTable("Schedules");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Settings.Setting", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Key")
                    .HasColumnType("integer");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("Id");

                b.HasIndex("Key")
                    .IsUnique();

                b.ToTable("Settings");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Soundclash", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("EndsAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTime>("LastModifiedDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("PerformerOneId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PerformerTwoId")
                    .HasColumnType("uuid");

                b.Property<string>("RoundOne")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RoundThree")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RoundTwo")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("ScheduleId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("StartsAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.HasIndex("PerformerOneId");

                b.HasIndex("PerformerTwoId");

                b.HasIndex("ScheduleId");

                b.ToTable("Soundclashes");
            });

        modelBuilder.Entity("LowPressureZone.Domain.NewsAggregate.News", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasMaxLength(16384)
                    .HasColumnType("character varying(16384)");

                b.Property<DateTimeOffset>("PublishedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.ToTable("News");
            });

        modelBuilder.Entity("LowPressureZone.Domain.PerformerAggregate.Performer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CreatorUserId")
                    .HasColumnType("uuid");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("SocialUrl")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.HasKey("Id");

                b.ToTable("Performers");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.ClashSlotEntity.ClashSlot", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("PerformerOneId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PerformerTwoId")
                    .HasColumnType("uuid");

                b.PrimitiveCollection<List<string>>("Rounds")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<Guid>("ScheduleId")
                    .HasColumnType("uuid");

                b.ComplexProperty(typeof(Dictionary<string, object>), "TimeRange", "LowPressureZone.Domain.ScheduleAggregate.ClashSlotEntity.ClashSlot.TimeRange#ClashTimeRange", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<int>("Duration")
                            .HasColumnType("integer");

                        b1.Property<DateTimeOffset>("EndsAt")
                            .HasColumnType("timestamp with time zone");

                        b1.Property<DateTimeOffset>("StartsAt")
                            .HasColumnType("timestamp with time zone");
                    });

                b.HasKey("Id");

                b.HasIndex("PerformerOneId");

                b.HasIndex("PerformerTwoId");

                b.HasIndex("ScheduleId");

                b.HasIndex("TimeRange.StartsAt")
                    .IsUnique();

                b.ToTable("ClashSlots");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.HourlySlotEntity.HourlySlot", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("PerformerId")
                    .HasColumnType("uuid");

                b.Property<Guid>("ScheduleId")
                    .HasColumnType("uuid");

                b.Property<string>("Subtitle")
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Prerecord", "LowPressureZone.Domain.ScheduleAggregate.HourlySlotEntity.HourlySlot.Prerecord#PrerecordedMix", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<int?>("AzuraCastMediaId")
                            .HasColumnType("integer");

                        b1.Property<bool>("IsPrerecorded")
                            .HasColumnType("boolean");

                        b1.Property<string>("UploadedFileName")
                            .HasMaxLength(2048)
                            .HasColumnType("character varying(2048)");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "TimeRange", "LowPressureZone.Domain.ScheduleAggregate.HourlySlotEntity.HourlySlot.TimeRange#HourlySlotTimeRange", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<int>("Duration")
                            .HasColumnType("integer");

                        b1.Property<DateTimeOffset>("EndsAt")
                            .HasColumnType("timestamp with time zone");

                        b1.Property<DateTimeOffset>("StartsAt")
                            .HasColumnType("timestamp with time zone");
                    });

                b.HasKey("Id");

                b.HasIndex("PerformerId");

                b.HasIndex("ScheduleId");

                b.HasIndex("TimeRange.StartsAt")
                    .IsUnique();

                b.ToTable("HourlySlots");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.Schedule", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("CommunityId")
                    .HasColumnType("uuid");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(16384)
                    .HasColumnType("character varying(16384)");

                b.Property<bool>("IsVisibleToPublic")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.ComplexProperty(typeof(Dictionary<string, object>), "AllowedSlotTypes", "LowPressureZone.Domain.ScheduleAggregate.Schedule.AllowedSlotTypes#AllowedScheduleSlotTypes", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<bool>("IsClashAllowed")
                            .HasColumnType("boolean");

                        b1.Property<bool>("IsHourlyAllowed")
                            .HasColumnType("boolean");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "TimeRange", "LowPressureZone.Domain.ScheduleAggregate.Schedule.TimeRange#ScheduleTimeRange", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<DateTimeOffset>("EndsAt")
                            .HasColumnType("timestamp with time zone");

                        b1.Property<DateTimeOffset>("StartsAt")
                            .HasColumnType("timestamp with time zone");
                    });

                b.HasKey("Id");

                b.HasIndex("CommunityId");

                b.HasIndex("TimeRange.StartsAt")
                    .IsUnique();

                b.ToTable("NewSchedules");
            });

        modelBuilder.Entity("LowPressureZone.Domain.CommunityAggregate.RelationshipEntity.Relationship", b =>
            {
                b.HasOne("LowPressureZone.Domain.CommunityAggregate.Community", "Community")
                    .WithMany("Relationships")
                    .HasForeignKey("CommunityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Community");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.CommunityRelationship", b =>
            {
                b.HasOne("LowPressureZone.Domain.Entities.Community", "Community")
                    .WithMany("Relationships")
                    .HasForeignKey("CommunityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Community");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.HourlySlot", b =>
            {
                b.HasOne("LowPressureZone.Domain.PerformerAggregate.Performer", "Performer")
                    .WithMany()
                    .HasForeignKey("PerformerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LowPressureZone.Domain.Entities.Schedule", "Schedule")
                    .WithMany("Timeslots")
                    .HasForeignKey("ScheduleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Performer");

                b.Navigation("Schedule");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Schedule", b =>
            {
                b.HasOne("LowPressureZone.Domain.Entities.Community", null)
                    .WithMany("Schedules")
                    .HasForeignKey("CommunityId");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Soundclash", b =>
            {
                b.HasOne("LowPressureZone.Domain.PerformerAggregate.Performer", "PerformerOne")
                    .WithMany()
                    .HasForeignKey("PerformerOneId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LowPressureZone.Domain.PerformerAggregate.Performer", "PerformerTwo")
                    .WithMany()
                    .HasForeignKey("PerformerTwoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LowPressureZone.Domain.Entities.Schedule", "Schedule")
                    .WithMany("Soundclashes")
                    .HasForeignKey("ScheduleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("PerformerOne");

                b.Navigation("PerformerTwo");

                b.Navigation("Schedule");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.ClashSlotEntity.ClashSlot", b =>
            {
                b.HasOne("LowPressureZone.Domain.PerformerAggregate.Performer", "PerformerOne")
                    .WithMany()
                    .HasForeignKey("PerformerOneId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .ExcludeForeignKeyFromMigrations(true);

                b.HasOne("LowPressureZone.Domain.PerformerAggregate.Performer", "PerformerTwo")
                    .WithMany()
                    .HasForeignKey("PerformerTwoId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .ExcludeForeignKeyFromMigrations(true);

                b.HasOne("LowPressureZone.Domain.ScheduleAggregate.Schedule", "Schedule")
                    .WithMany("ClashSlots")
                    .HasForeignKey("ScheduleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .ExcludeForeignKeyFromMigrations(true);

                b.Navigation("PerformerOne");

                b.Navigation("PerformerTwo");

                b.Navigation("Schedule");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.HourlySlotEntity.HourlySlot", b =>
            {
                b.HasOne("LowPressureZone.Domain.PerformerAggregate.Performer", "Performer")
                    .WithMany()
                    .HasForeignKey("PerformerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .ExcludeForeignKeyFromMigrations(true);

                b.HasOne("LowPressureZone.Domain.ScheduleAggregate.Schedule", "Schedule")
                    .WithMany("HourlySlots")
                    .HasForeignKey("ScheduleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .ExcludeForeignKeyFromMigrations(true);

                b.Navigation("Performer");

                b.Navigation("Schedule");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.Schedule", b =>
            {
                b.HasOne("LowPressureZone.Domain.CommunityAggregate.Community", "Community")
                    .WithMany()
                    .HasForeignKey("CommunityId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .ExcludeForeignKeyFromMigrations(true);

                b.Navigation("Community");
            });

        modelBuilder.Entity("LowPressureZone.Domain.CommunityAggregate.Community", b =>
            {
                b.Navigation("Relationships");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Community", b =>
            {
                b.Navigation("Relationships");

                b.Navigation("Schedules");
            });

        modelBuilder.Entity("LowPressureZone.Domain.Entities.Schedule", b =>
            {
                b.Navigation("Soundclashes");

                b.Navigation("Timeslots");
            });

        modelBuilder.Entity("LowPressureZone.Domain.ScheduleAggregate.Schedule", b =>
            {
                b.Navigation("ClashSlots");

                b.Navigation("HourlySlots");
            });
#pragma warning restore 612, 618
    }
}
