services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: l0wpressure
      POSTGRES_DB: defaultdb  # Required by image, but we'll create our own databases in the init-db script
    ports:
      - "5432:5432"
    volumes:
      - lpz:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U postgres -d postgres || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5433
    ports: 
      - "5433:5433"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  icecast2:
    image: pltnk/icecast2:latest
    container_name: icecast2
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./icecast2/icecast.xml:/etc/icecast.xml

volumes: #stores database locally so it persists between restarts. Can be removed with 'docker-compose down -v' command
  lpz:
  pgadmin-data: