<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.SmartEnum" Version="8.2.0"/>
        <PackageReference Include="Ardalis.SmartEnum.EFCore" Version="8.2.0"/>
        <PackageReference Include="Ardalis.SmartEnum.SystemTextJson" Version="8.1.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="11.0.0-preview.6.26359.118" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="11.0.0-preview.6.26359.118" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="11.0.0-preview.6.26359.118">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="11.0.0-preview.6" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ScheduleAggregate\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LowPressureZone.Core\LowPressureZone.Core.csproj" />
    </ItemGroup>

</Project>
